In [ ]:
!pip install torch # Установка библеотеки PyTorch

In [ ]:
import torch

Основная структура данных для Torch - это **тензоры**(многомерная матрица).

In [ ]:
torch.zeros([3, 4]) # Создаем тензор рамера 3(строки)*4(столбца) - заполненную НУЛЯМИ

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones([3, 4, 3]) # создаем тензор, заполненный единицами(размером 3(плоскости)*4(строчки)*3(столбика))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

# Далее приведен пример создание произвольного Тензора при пощи передачи методу тензор объект список.

In [ ]:
x = torch.Tensor([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

Приведены две функции для определения размера тензора

In [ ]:
x.size()

torch.Size([3, 4])

In [ ]:
x.shape

torch.Size([3, 4])

In [ ]:
x[0]

tensor([1., 2., 3., 4.])

In [ ]:
x[1]

tensor([5., 6., 7., 8.])

In [ ]:
x[:, 0]

tensor([1., 5., 9.])

# Операции для тензора

In [ ]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [ ]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [ ]:
y = torch.Tensor([[12, 11, 10, 9],
                 [8, 7, 6, 5],
                 [4, 3, 2, 1]])

In [ ]:
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [ ]:
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [ ]:
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [ ]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

Есть все математические функции

In [ ]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [ ]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [ ]:
mask = x > 3

In [ ]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

# Копирование

In [ ]:
y = x
y[0, 0] = 999
print(x)
print(y)

# Такой вид копирования называется копированием по ссылке, те на объект в памяти х начинает ссылать еще и переменная у.

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [ ]:
x = torch.Tensor([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

In [ ]:
y = x.clone()
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [ ]:
x.dtype # -> Дробные чмсла занимающие 32 бита информации

torch.float32

In [ ]:
x = x.double() # -> dtype=torch.float64 
print(x)
x = x.int() # -> dtype=torch.int32
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


# Работа с тензорами в Numpy

In [ ]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

## Работа с GPU

In [ ]:
x = torch.rand([2000, 3000])
x

tensor([[0.1251, 0.1661, 0.7902,  ..., 0.2697, 0.3735, 0.7981],
        [0.0070, 0.7523, 0.6766,  ..., 0.5429, 0.2852, 0.6547],
        [0.0491, 0.5192, 0.7048,  ..., 0.3728, 0.0788, 0.7631],
        ...,
        [0.9416, 0.4514, 0.5687,  ..., 0.7092, 0.5613, 0.9748],
        [0.4496, 0.5204, 0.8142,  ..., 0.5945, 0.3847, 0.8408],
        [0.9902, 0.6120, 0.0823,  ..., 0.9471, 0.3219, 0.1824]])

In [ ]:
torch.cuda.is_available()

True

Чтобы перевести на другой девайс нужно создать объект девайс.

In [ ]:
torch.device('cuda:0') # Этот девайс отвечает видеокарте

device(type='cuda', index=0)

In [ ]:
torch.device('cpu') # перевод с видеокарты на CPU

device(type='cpu')

Универсальная команда для перевода торч тензора на ту платформу, которая у нас есть в компьютере

In [ ]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [ ]:
x_cuda = x.to(device)
x_cuda

tensor([[0.1251, 0.1661, 0.7902,  ..., 0.2697, 0.3735, 0.7981],
        [0.0070, 0.7523, 0.6766,  ..., 0.5429, 0.2852, 0.6547],
        [0.0491, 0.5192, 0.7048,  ..., 0.3728, 0.0788, 0.7631],
        ...,
        [0.9416, 0.4514, 0.5687,  ..., 0.7092, 0.5613, 0.9748],
        [0.4496, 0.5204, 0.8142,  ..., 0.5945, 0.3847, 0.8408],
        [0.9902, 0.6120, 0.0823,  ..., 0.9471, 0.3219, 0.1824]],
       device='cuda:0')

Проверка времени выполнения на CPU

In [ ]:
%time y = (x - x + x * 10.0) ** 2

CPU times: user 28 ms, sys: 24.4 ms, total: 52.5 ms
Wall time: 65.5 ms


DEVICE:

In [ ]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 0 ns, sys: 1.41 ms, total: 1.41 ms
Wall time: 3.4 ms
